/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MerchantLoginRouteImport } from './routes/merchant-login'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIdRouteImport } from './routes/store.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as MerchantDashboardRouteImport } from './routes/merchant.dashboard'
import { Route as CategoryKeyRouteImport } from './routes/category.$key'
import { Route as ApplyMerchantRouteImport } from './routes/apply.merchant'
import { Route as ApplyDriverRouteImport } from './routes/apply.driver'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantLoginRoute = MerchantLoginRouteImport.update({
  id: '/merchant-login',
  path: '/merchant-login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIdRoute = StoreIdRouteImport.update({
  id: '/store/$id',
  path: '/store/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantDashboardRoute = MerchantDashboardRouteImport.update({
  id: '/merchant/dashboard',
  path: '/merchant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryKeyRoute = CategoryKeyRouteImport.update({
  id: '/category/$key',
  path: '/category/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyMerchantRoute = ApplyMerchantRouteImport.update({
  id: '/apply/merchant',
  path: '/apply/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyDriverRoute = ApplyDriverRouteImport.update({
  id: '/apply/driver',
  path: '/apply/driver',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/merchant-login': typeof MerchantLoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/apply/driver': typeof ApplyDriverRoute
  '/apply/merchant': typeof ApplyMerchantRoute
  '/category/$key': typeof CategoryKeyRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/store/$id': typeof StoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/merchant-login': typeof MerchantLoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/apply/driver': typeof ApplyDriverRoute
  '/apply/merchant': typeof ApplyMerchantRoute
  '/category/$key': typeof CategoryKeyRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/store/$id': typeof StoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/merchant-login': typeof MerchantLoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/apply/driver': typeof ApplyDriverRoute
  '/apply/merchant': typeof ApplyMerchantRoute
  '/category/$key': typeof CategoryKeyRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/store/$id': typeof StoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/merchant-login'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/sitemap.xml'
    | '/apply/driver'
    | '/apply/merchant'
    | '/category/$key'
    | '/merchant/dashboard'
    | '/order/$id'
    | '/product/$id'
    | '/store/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/merchant-login'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/sitemap.xml'
    | '/apply/driver'
    | '/apply/merchant'
    | '/category/$key'
    | '/merchant/dashboard'
    | '/order/$id'
    | '/product/$id'
    | '/store/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/merchant-login'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/sitemap.xml'
    | '/apply/driver'
    | '/apply/merchant'
    | '/category/$key'
    | '/merchant/dashboard'
    | '/order/$id'
    | '/product/$id'
    | '/store/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  MerchantLoginRoute: typeof MerchantLoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApplyDriverRoute: typeof ApplyDriverRoute
  ApplyMerchantRoute: typeof ApplyMerchantRoute
  CategoryKeyRoute: typeof CategoryKeyRoute
  MerchantDashboardRoute: typeof MerchantDashboardRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductIdRoute: typeof ProductIdRoute
  StoreIdRoute: typeof StoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-login': {
      id: '/merchant-login'
      path: '/merchant-login'
      fullPath: '/merchant-login'
      preLoaderRoute: typeof MerchantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$id': {
      id: '/store/$id'
      path: '/store/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof StoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/dashboard': {
      id: '/merchant/dashboard'
      path: '/merchant/dashboard'
      fullPath: '/merchant/dashboard'
      preLoaderRoute: typeof MerchantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$key': {
      id: '/category/$key'
      path: '/category/$key'
      fullPath: '/category/$key'
      preLoaderRoute: typeof CategoryKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/merchant': {
      id: '/apply/merchant'
      path: '/apply/merchant'
      fullPath: '/apply/merchant'
      preLoaderRoute: typeof ApplyMerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/driver': {
      id: '/apply/driver'
      path: '/apply/driver'
      fullPath: '/apply/driver'
      preLoaderRoute: typeof ApplyDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  MerchantLoginRoute: MerchantLoginRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApplyDriverRoute: ApplyDriverRoute,
  ApplyMerchantRoute: ApplyMerchantRoute,
  CategoryKeyRoute: CategoryKeyRoute,
  MerchantDashboardRoute: MerchantDashboardRoute,
  OrderIdRoute: OrderIdRoute,
  ProductIdRoute: ProductIdRoute,
  StoreIdRoute: StoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
